name: "📝 Software development task"
description: "Software development task with definition of done (DoD) checklist"
title: "[TASK] "
labels: [task]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "📌 Description"
      description: "Describe the task and what needs to be done"
      placeholder: "Describe the essence of the task..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ Checklist"
      options:
        - label: "The task is implemented according to the requirements."
        - label: "The code is covered with unit tests."
        - label: "Static code analysis has been completed with no critical issues."
        - label: "A pull request has been created."
        - label: "The code has passed the code review."
        - label: "The pull request has been successfully merged."
